// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkillBridge.Message {

  /// <summary>Holder for reflection information generated from chat.proto</summary>
  public static partial class ChatReflection {

    #region Descriptor
    /// <summary>File descriptor for chat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpjaGF0LnByb3RvEhNTa2lsbEJyaWRnZS5NZXNzYWdlGgpiYXNlLnByb3Rv",
            "IkAKC0NoYXRSZXF1ZXN0EjEKB21lc3NhZ2UYASABKAsyIC5Ta2lsbEJyaWRn",
            "ZS5NZXNzYWdlLkNoYXRNZXNzYWdlIqUDCgxDaGF0UmVzcG9uc2USKwoGcmVz",
            "dWx0GAEgASgOMhsuU2tpbGxCcmlkZ2UuTWVzc2FnZS5SZXN1bHQSEAoIZXJy",
            "b3Jtc2cYAiABKAkSNwoNbG9jYWxNZXNzYWdlcxgDIAMoCzIgLlNraWxsQnJp",
            "ZGdlLk1lc3NhZ2UuQ2hhdE1lc3NhZ2USNwoNd29ybGRNZXNzYWdlcxgEIAMo",
            "CzIgLlNraWxsQnJpZGdlLk1lc3NhZ2UuQ2hhdE1lc3NhZ2USOAoOc3lzdGVt",
            "TWVzc2FnZXMYBSADKAsyIC5Ta2lsbEJyaWRnZS5NZXNzYWdlLkNoYXRNZXNz",
            "YWdlEjkKD3ByaXZhdGVNZXNzYWdlcxgGIAMoCzIgLlNraWxsQnJpZGdlLk1l",
            "c3NhZ2UuQ2hhdE1lc3NhZ2USNgoMdGVhbU1lc3NhZ2VzGAcgAygLMiAuU2tp",
            "bGxCcmlkZ2UuTWVzc2FnZS5DaGF0TWVzc2FnZRI3Cg1ndWlsZE1lc3NhZ2Vz",
            "GAggAygLMiAuU2tpbGxCcmlkZ2UuTWVzc2FnZS5DaGF0TWVzc2FnZUIZ+AEB",
            "qgITU2tpbGxCcmlkZ2UuTWVzc2FnZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SkillBridge.Message.BaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SkillBridge.Message.ChatRequest), global::SkillBridge.Message.ChatRequest.Parser, new[]{ "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkillBridge.Message.ChatResponse), global::SkillBridge.Message.ChatResponse.Parser, new[]{ "Result", "Errormsg", "LocalMessages", "WorldMessages", "SystemMessages", "PrivateMessages", "TeamMessages", "GuildMessages" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChatRequest : pb::IMessage<ChatRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatRequest> _parser = new pb::MessageParser<ChatRequest>(() => new ChatRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkillBridge.Message.ChatReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatRequest(ChatRequest other) : this() {
      message_ = other.message_ != null ? other.message_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatRequest Clone() {
      return new ChatRequest(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private global::SkillBridge.Message.ChatMessage message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SkillBridge.Message.ChatMessage Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Message, other.Message)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (message_ != null) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (message_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (message_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatRequest other) {
      if (other == null) {
        return;
      }
      if (other.message_ != null) {
        if (message_ == null) {
          Message = new global::SkillBridge.Message.ChatMessage();
        }
        Message.MergeFrom(other.Message);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (message_ == null) {
              Message = new global::SkillBridge.Message.ChatMessage();
            }
            input.ReadMessage(Message);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (message_ == null) {
              Message = new global::SkillBridge.Message.ChatMessage();
            }
            input.ReadMessage(Message);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChatResponse : pb::IMessage<ChatResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatResponse> _parser = new pb::MessageParser<ChatResponse>(() => new ChatResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkillBridge.Message.ChatReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatResponse(ChatResponse other) : this() {
      result_ = other.result_;
      errormsg_ = other.errormsg_;
      localMessages_ = other.localMessages_.Clone();
      worldMessages_ = other.worldMessages_.Clone();
      systemMessages_ = other.systemMessages_.Clone();
      privateMessages_ = other.privateMessages_.Clone();
      teamMessages_ = other.teamMessages_.Clone();
      guildMessages_ = other.guildMessages_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatResponse Clone() {
      return new ChatResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::SkillBridge.Message.Result result_ = global::SkillBridge.Message.Result.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SkillBridge.Message.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "errormsg" field.</summary>
    public const int ErrormsgFieldNumber = 2;
    private string errormsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Errormsg {
      get { return errormsg_; }
      set {
        errormsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "localMessages" field.</summary>
    public const int LocalMessagesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::SkillBridge.Message.ChatMessage> _repeated_localMessages_codec
        = pb::FieldCodec.ForMessage(26, global::SkillBridge.Message.ChatMessage.Parser);
    private readonly pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> localMessages_ = new pbc::RepeatedField<global::SkillBridge.Message.ChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> LocalMessages {
      get { return localMessages_; }
    }

    /// <summary>Field number for the "worldMessages" field.</summary>
    public const int WorldMessagesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::SkillBridge.Message.ChatMessage> _repeated_worldMessages_codec
        = pb::FieldCodec.ForMessage(34, global::SkillBridge.Message.ChatMessage.Parser);
    private readonly pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> worldMessages_ = new pbc::RepeatedField<global::SkillBridge.Message.ChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> WorldMessages {
      get { return worldMessages_; }
    }

    /// <summary>Field number for the "systemMessages" field.</summary>
    public const int SystemMessagesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::SkillBridge.Message.ChatMessage> _repeated_systemMessages_codec
        = pb::FieldCodec.ForMessage(42, global::SkillBridge.Message.ChatMessage.Parser);
    private readonly pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> systemMessages_ = new pbc::RepeatedField<global::SkillBridge.Message.ChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> SystemMessages {
      get { return systemMessages_; }
    }

    /// <summary>Field number for the "privateMessages" field.</summary>
    public const int PrivateMessagesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::SkillBridge.Message.ChatMessage> _repeated_privateMessages_codec
        = pb::FieldCodec.ForMessage(50, global::SkillBridge.Message.ChatMessage.Parser);
    private readonly pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> privateMessages_ = new pbc::RepeatedField<global::SkillBridge.Message.ChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> PrivateMessages {
      get { return privateMessages_; }
    }

    /// <summary>Field number for the "teamMessages" field.</summary>
    public const int TeamMessagesFieldNumber = 7;
    private static readonly pb::FieldCodec<global::SkillBridge.Message.ChatMessage> _repeated_teamMessages_codec
        = pb::FieldCodec.ForMessage(58, global::SkillBridge.Message.ChatMessage.Parser);
    private readonly pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> teamMessages_ = new pbc::RepeatedField<global::SkillBridge.Message.ChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> TeamMessages {
      get { return teamMessages_; }
    }

    /// <summary>Field number for the "guildMessages" field.</summary>
    public const int GuildMessagesFieldNumber = 8;
    private static readonly pb::FieldCodec<global::SkillBridge.Message.ChatMessage> _repeated_guildMessages_codec
        = pb::FieldCodec.ForMessage(66, global::SkillBridge.Message.ChatMessage.Parser);
    private readonly pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> guildMessages_ = new pbc::RepeatedField<global::SkillBridge.Message.ChatMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillBridge.Message.ChatMessage> GuildMessages {
      get { return guildMessages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (Errormsg != other.Errormsg) return false;
      if(!localMessages_.Equals(other.localMessages_)) return false;
      if(!worldMessages_.Equals(other.worldMessages_)) return false;
      if(!systemMessages_.Equals(other.systemMessages_)) return false;
      if(!privateMessages_.Equals(other.privateMessages_)) return false;
      if(!teamMessages_.Equals(other.teamMessages_)) return false;
      if(!guildMessages_.Equals(other.guildMessages_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::SkillBridge.Message.Result.Success) hash ^= Result.GetHashCode();
      if (Errormsg.Length != 0) hash ^= Errormsg.GetHashCode();
      hash ^= localMessages_.GetHashCode();
      hash ^= worldMessages_.GetHashCode();
      hash ^= systemMessages_.GetHashCode();
      hash ^= privateMessages_.GetHashCode();
      hash ^= teamMessages_.GetHashCode();
      hash ^= guildMessages_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::SkillBridge.Message.Result.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Errormsg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Errormsg);
      }
      localMessages_.WriteTo(output, _repeated_localMessages_codec);
      worldMessages_.WriteTo(output, _repeated_worldMessages_codec);
      systemMessages_.WriteTo(output, _repeated_systemMessages_codec);
      privateMessages_.WriteTo(output, _repeated_privateMessages_codec);
      teamMessages_.WriteTo(output, _repeated_teamMessages_codec);
      guildMessages_.WriteTo(output, _repeated_guildMessages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::SkillBridge.Message.Result.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Errormsg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Errormsg);
      }
      localMessages_.WriteTo(ref output, _repeated_localMessages_codec);
      worldMessages_.WriteTo(ref output, _repeated_worldMessages_codec);
      systemMessages_.WriteTo(ref output, _repeated_systemMessages_codec);
      privateMessages_.WriteTo(ref output, _repeated_privateMessages_codec);
      teamMessages_.WriteTo(ref output, _repeated_teamMessages_codec);
      guildMessages_.WriteTo(ref output, _repeated_guildMessages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::SkillBridge.Message.Result.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (Errormsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Errormsg);
      }
      size += localMessages_.CalculateSize(_repeated_localMessages_codec);
      size += worldMessages_.CalculateSize(_repeated_worldMessages_codec);
      size += systemMessages_.CalculateSize(_repeated_systemMessages_codec);
      size += privateMessages_.CalculateSize(_repeated_privateMessages_codec);
      size += teamMessages_.CalculateSize(_repeated_teamMessages_codec);
      size += guildMessages_.CalculateSize(_repeated_guildMessages_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::SkillBridge.Message.Result.Success) {
        Result = other.Result;
      }
      if (other.Errormsg.Length != 0) {
        Errormsg = other.Errormsg;
      }
      localMessages_.Add(other.localMessages_);
      worldMessages_.Add(other.worldMessages_);
      systemMessages_.Add(other.systemMessages_);
      privateMessages_.Add(other.privateMessages_);
      teamMessages_.Add(other.teamMessages_);
      guildMessages_.Add(other.guildMessages_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::SkillBridge.Message.Result) input.ReadEnum();
            break;
          }
          case 18: {
            Errormsg = input.ReadString();
            break;
          }
          case 26: {
            localMessages_.AddEntriesFrom(input, _repeated_localMessages_codec);
            break;
          }
          case 34: {
            worldMessages_.AddEntriesFrom(input, _repeated_worldMessages_codec);
            break;
          }
          case 42: {
            systemMessages_.AddEntriesFrom(input, _repeated_systemMessages_codec);
            break;
          }
          case 50: {
            privateMessages_.AddEntriesFrom(input, _repeated_privateMessages_codec);
            break;
          }
          case 58: {
            teamMessages_.AddEntriesFrom(input, _repeated_teamMessages_codec);
            break;
          }
          case 66: {
            guildMessages_.AddEntriesFrom(input, _repeated_guildMessages_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::SkillBridge.Message.Result) input.ReadEnum();
            break;
          }
          case 18: {
            Errormsg = input.ReadString();
            break;
          }
          case 26: {
            localMessages_.AddEntriesFrom(ref input, _repeated_localMessages_codec);
            break;
          }
          case 34: {
            worldMessages_.AddEntriesFrom(ref input, _repeated_worldMessages_codec);
            break;
          }
          case 42: {
            systemMessages_.AddEntriesFrom(ref input, _repeated_systemMessages_codec);
            break;
          }
          case 50: {
            privateMessages_.AddEntriesFrom(ref input, _repeated_privateMessages_codec);
            break;
          }
          case 58: {
            teamMessages_.AddEntriesFrom(ref input, _repeated_teamMessages_codec);
            break;
          }
          case 66: {
            guildMessages_.AddEntriesFrom(ref input, _repeated_guildMessages_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
